version: '3'
services:
  postgres:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_DATABASE}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  cow-api-dev:
    image: cow-api-dev
    container_name: cow-api
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
    ports: 
      - 3000:3000
    environment:
      - ENV
      - PORT
      - DATABASE_HOST=postgres
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_DATABASE
      - JWT_SECRET
      - JWT_EXPIRESIN
